version: 0.2

env:
  variables:
    TARGET_REGION: "us-east-1"
    deployRoleArn: "arn:aws:iam::611394351971:role/Deployer"
    paramRoleArn: "arn:aws:iam::083255287042:role/platform-api-param-access"
    cloudType: "public"
phases:
  install:
    commands:
      - apt-get update
      - apt-get install p7zip-full
      - npm install npm@latest -g
      - echo Running NPM setup
      - cd deployment/setup-npm
      - npm install
      - npm run setup-npm -- --role-arn $paramRoleArn --region $TARGET_REGION
      - cd ../..
  pre_build:
    commands:
      - echo Installing packages for API-Gateway
      - cd api
      - npm install
      - cd ..
      - echo Installing packages for deployment
      - cd deployment
      - npm install
      - npm i @mitel-internal/cloudlink-deployment@latest
      - cd ..
  build:
    commands:
      - echo Build and Deployment started on `date`
      - cd deployment
      - npm config set platform-api-x:region $TARGET_REGION
      - npm config set platform-api-x:cloud $cloudType
      - npm config set platform-api-x:roleArn $deployRoleArn
      - npm run deploy
      - cd ..
      - echo Build and Deployment completed on `date`
artifacts:
  files:
    - api/build/**/*
    - deployment/build/**/*